### PR TITLE
Add spect integration tests

### PR DESCRIPTION
**Pull request by chrisguttandin**
Hi @dy, could you please take a look if that looks correct? If so I would continue adding an integration test for each subscribable thing.

One thing I noticed is that calling `[Symbol.dispose]()` doesn't call `unsubscribe()` on the underlying observable. Should I open a separate issue for that on [spectjs/spec](https://github.com/spectjs/spec)?

### CODE REVIEW

**Comment by dy** [comment]
Hmm, it should call unsubscribe. I can try to debug. Do you have some particular short example?

**Comment by chrisguttandin** [comment]
You can use any of the new tests. Does that help?

**Comment by dy** [comment]
Ok, git fix in spect@23.1.1

**Comment by dy** [comment]
Interesting. Should have a look at safari, mb the issue is spect again.

**Comment by chrisguttandin** [comment]
Nono, I think this is because the Safari on BrowserStack has no media devices which it could show.

Many thanks for your quick fix. I will keep on adding more integration tests and fixing that for media devices.

**Comment by chrisguttandin** [comment]
It looks like it works great now. Could you please take another look, @dy?

**Comment by dy** [comment]
That's laborious work 👍
I'd like to know your opinion on Symbol.dispose. I was refusing to extend elements with .dispose or .unsubscribe methods, but dyk if there are patterns in that regard in reactive world?

**Comment by chrisguttandin** [comment]
Thanks for checking again.

I agree, I also think it's a good idea to not extend native HTML elements.

As far as I know this functionality is mostly called `unsubscribe`. But naming it differently seems to be okay for me since it does a bit of a different thing or is at least called in a different context.

If you want to get rid of the `Symbol.dispose` you could export a function called `dispose()`. That function would take an HTML element as a parameter and look for an active subscription stored in a `WeakMap`. And if there is one it will unsubscribe from that subscription and delete it.

```js
const subscriptions = new WeakMap();

// ... somewhere subscriptions get stored
subscriptions.add(element, sub);

export const dispose = (element) => {
    subscriptions.get(element)?.unsubscribe();
    subscriptions.delete(element);
};
```

It's just an idea. Feel free to ignore it.

**Comment by dy** [comment]
Thanks!
I was considering that, but decided to make API radically minimal, to match user intuition. But I suppose there's no intuition for destructor methods yet, Symbol.dispose is the best standard attempt I found.

**Comment by chrisguttandin** [comment]
Okay, I see. I guess subscribing and unsubscribing automatically based on something like the presence in the DOM (maybe by using a `MutationObserver` or [`mutations()`](https://github.com/chrisguttandin/subscribable-things#mutationshtmlelement-htmlelement-options-mutationobserverinit-subscribablethingmutationrecord)) would be too magical, right?

**Pull request merged**
